package controlador;
import Vista.*;
import vista.JInternalFrameProveedor;

/** @author ferreteria icon
 */
public class sistemaiconMDI extends javax.swing.JFrame {
    private final JInternalFrameProveedor Proveedor;
    /**/
    public sistemaiconMDI() {
        initComponents();
        setTitle("Registros");
        Proveedor= new JInternalFrameProveedor();
        desktopPane.add(Proveedor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MenuItemproveedor = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu2 = new javax.swing.JMenu();
        MenuItem2cliente = new javax.swing.JMenuItem();
        editMenu1 = new javax.swing.JMenu();
        MenuItem1productos = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        MenuItem1ventas = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        MenuItemfactura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 102, 0));

        fileMenu.setMnemonic('f');
        fileMenu.setText("proveedores");
        fileMenu.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        MenuItemproveedor.setMnemonic('o');
        MenuItemproveedor.setText("ver provedores");
        MenuItemproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemproveedorActionPerformed(evt);
            }
        });
        fileMenu.add(MenuItemproveedor);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu2.setMnemonic('e');
        editMenu2.setText("cliente");
        editMenu2.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        MenuItem2cliente.setMnemonic('t');
        MenuItem2cliente.setText("ver cliente");
        editMenu2.add(MenuItem2cliente);

        menuBar.add(editMenu2);

        editMenu1.setMnemonic('e');
        editMenu1.setText("productos");
        editMenu1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        MenuItem1productos.setMnemonic('t');
        MenuItem1productos.setText("ver productos");
        editMenu1.add(MenuItem1productos);

        menuBar.add(editMenu1);

        helpMenu1.setMnemonic('h');
        helpMenu1.setText("ventas");
        helpMenu1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        MenuItem1ventas.setMnemonic('c');
        MenuItem1ventas.setText("ver ventas");
        helpMenu1.add(MenuItem1ventas);

        menuBar.add(helpMenu1);

        helpMenu.setMnemonic('h');
        helpMenu.setText("facturacion");
        helpMenu.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        MenuItemfactura.setMnemonic('c');
        MenuItemfactura.setText("ver factura");
        helpMenu.add(MenuItemfactura);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void MenuItemproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemproveedorActionPerformed
        Proveedor.obtenerDatos();
        Proveedor.setVisible(true);
    }//GEN-LAST:event_MenuItemproveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistemasregistrosMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistemasregistrosMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistemasregistrosMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistemasregistrosMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistemaiconMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem1productos;
    private javax.swing.JMenuItem MenuItem1ventas;
    private javax.swing.JMenuItem MenuItem2cliente;
    private javax.swing.JMenuItem MenuItemfactura;
    private javax.swing.JMenuItem MenuItemproveedor;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenu editMenu2;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
